//gets all events
GET http://localhost:8080/events/all HTTP/1.1

###

//gets all deviceGroups asociated with a single event
// url param (eventId) required
GET http://localhost:8080/events/unique?eventID=1 HTTP/1.1

###
// creates new Events
POST http://localhost:8080/events/new HTTP/1.1
Content-Type: application/json

{
    "creatorID": 1,
    "customerID": 0,
    "customerName": "Harald Günter",
    "customerStreetNum": "Bergstraße 5",
    "customerCity": "Tann",
    "name": "TestEvent",
    "adress": "Am Joßberg 11, 36142 Tann",
    "startDate": "2022-07-31T09:24:00",
    "endDate": "2022-08-01T12:00:00"
}

###

// adding Devices to Events
PATCH http://localhost:8080/events/addDevice HTTP/1.1
Content-Type: application/json

{
    "eventID": 1,
    "deviceGroupID": 2
}